# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2981bf9aec9532bff3df6733137bb637e373a284bb8921408b794495604eeed26f1d3aa594327624cc8db5a4db46b363480e1b348d017d3d994df05d2655555a

test:
  secret_key_base: 945603cd53cceaca0cb351268645c522d5fe82f8a3f0c6f9469254dcdf985f9fdf105b091a908725de66e03bf2249cbb4e64501e9a6eccbc5334aa252824c5fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
